### ISSUE TITLE
windowsで動作させたとき、99%で止まってしまう

### ISSUE THREAD

**Issue by dmrmuu** [vitroid/TrainScanner#16]
スタートを押した後、プレビュー画面でステータスバーが99%のところで止まってしまいます。
install方法が間違っているのでしょうか？お忙しいところ申し訳ありませんが、直す方法をご存じでしたら教えていただけると幸いです。よろしくお願いします。

環境
windows10 64bit
CPU:intel i5-7500 3.4GHz
メモリ:16GB
ドライブ空き容量:2.5TB
anaconda3 windows64bit python3.7版
動画ファイル形式:mp4

他に試したこと
・anaconda3のpythonを3.5にダウングレード
・TrainScanner.exeを管理者権限で実行

**Comment by vitroid** [comment]
承知しました。もう長いことWindowsで実行していないので、ライブラリ等との相性が悪くなっているのかもしれませんね。確認します。

**Comment by vitroid** [comment]
いろいろ古くなっていることがわかりましたので手直ししました。0.12.0をインストールして試していただけないでしょうか。

**Comment by dmrmuu** [comment]
対応いただきありがとうございます。
0.12.0を起動しましたところ、プレビュー画面が起動すると同時にソフトが落ちるようになりました。
anaconda3をリインストールしても同じ状況です。
原因かわかりませんが、trainscannerフォルダ内のpythonのバージョンが3.8.3になってました。この辺のダウングレードはまだ試していませんが、私も可能な限りいろいろ試してみれればと思います。
申し訳ありませんがよろしくお願いいたします。

**Comment by vitroid** [comment]
スレッド処理のタイミングが合っていない感じですね。たしかにWindowsでしばしば止まります。もう少し調べます。

**Comment by vitroid** [comment]
AnacondaのEnvironmentsからOpen Terminalして、コマンドラインに trainscanner と打ちこんで起動し、パネルでDebugボタンを押した状態でビデオの処理をすると、terminalにいろいろ情報が表示されると思います。落ちる直前のメッセージを教えていただけないでしょうか。

**Comment by dmrmuu** [comment]
引き続きご迷惑おかけして申し訳ありません。
落ちる際のメッセージを送らせていただきます。よろしくお願いいたします。


-----以下エラーメッセージ-----
[ERROR:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap.cpp (142) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): C:/Users/******/New in function 'cv::icvExtractPattern'


Traceback (most recent call last):
  File "E:\soft\anaconda3\envs\trainscanner\lib\site-packages\trainscanner\stitch_gui.py", line 40, in task
    for num,den in self.stitcher.before():
  File "E:\soft\anaconda3\envs\trainscanner\lib\site-packages\trainscanner\stitch.py", line 181, in before
    tspos = open(self.tsposfile)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/******/New.tspos'
-----以上エラーメッセージ-----

なお、元動画の保存先は'C:/User/******/New folder'です。

**Comment by vitroid** [comment]
ありがとうございます。大変参考になります。もしかして、フォルダ名を"New folder"ではなく"Newfolder" (空白なし)にすると動くでしょうか?

**Comment by dmrmuu** [comment]
空白を無くしたら動きました。また、無事100％まで動作し、finishボタンで終了することができました。
プログラムでフォルダ名の空白が弱点なのを忘れておりました…初歩的なことで申し訳ありませんでした。
これからいろんな列車の側面を撮影したいと思います。ありがとうございます！
また、重ねてtrainscannerの開発をしていただきありがとうございます。引き続きお世話になります。よろしくお願いいたします！

**Comment by vitroid** [comment]
パス名に空白が入っていると落ちるバグを修正し、0.12.3としてPyPIにアップロードしました。Terminalから、
pip install -U trainscanner
でパッケージがアップデートされると思います。バグ報告ありがとうございました。作品を楽しみにしています。
